version: 0.1
phases:
  build:
    commands:
      - echo Build starts `date`
      - sbt compile assembly
  install:
    commands:
      - mkdir -p deploy/lib
      - cp target/scala-2.12/awsLambda.jar deploy/lib
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambda-codedeploy-test1 --output-template-file NewSamTemplate.yaml || exit 0
artifacts:
  type: zip
  files:
    - deploy/lib/awsLambda.jar
    - NewSamTemplate.yaml

