version: 0.2

phases:
  build:
    commands:
      - echo build `date`
      - sbt compile assembly
  post_build:
    commands:
      - echo post_build `date`
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambda-codedeploy-test1 --output-template-file NewSamTemplate.yaml || exit 0
artifacts:
  type: zip
  files:
    - target/scala-2.12/awsLambda.jar
    - NewSamTemplate.yaml

