AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time 3
Resources:
  scala3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'example.EventHandler::processEvent'
      Runtime: java8
      CodeUri: target/scala-2.12/awsLambda.jar
      Description: ''
      MemorySize: 192
      Timeout: 15
